const fs = require('fs');
const path = require('path');

console.log('🚀 Starting to fix favicons for KTRH website...\n');
console.log('📂 Favicons are located in: img/favicon_io3/\n');

// Favicon HTML code with CORRECT paths to img/favicon_io3/
const faviconCode = `
    <!-- ======= KTRH FAVICON ======= -->
    <!-- Generated by favicon.io - Located in img/favicon_io/ -->
    <link rel="apple-touch-icon" sizes="180x180" href="img/favicon_io/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/favicon_io/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/favicon_io/favicon-16x16.png">
    <link rel="manifest" href="img/favicon_io/site.webmanifest">
    <link rel="mask-icon" href="img/favicon_io/safari-pinned-tab.svg" color="#5bbad5">
    <link rel="shortcut icon" href="img/favicon_io/favicon.ico">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-config" content="img/favicon_io/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">
    <!-- ======= END FAVICON ======= -->`;

// All HTML files in your project
const htmlFiles = [
    'index.html',
    'about.html',
    'services.html',
    'departments.html',
    'doctors.html',
    'projects.html',
    'gallery.html',
    'careers.html',
    'contact.html',
    'appointment.html'
];

let updatedCount = 0;
let skippedCount = 0;
let errorCount = 0;

console.log('📝 Processing HTML files:\n');

htmlFiles.forEach(file => {
    const filePath = path.join(__dirname, file);
    
    if (!fs.existsSync(filePath)) {
        console.log(`❌ ${file}: File not found`);
        errorCount++;
        return;
    }
    
    try {
        let content = fs.readFileSync(filePath, 'utf8');
        
        // Check if favicon code already exists
        if (content.includes('favicon_io3') || 
            content.includes('apple-touch-icon') || 
            content.includes('favicon.ico')) {
            console.log(`⏭️  ${file}: Already has favicon code, skipping...`);
            skippedCount++;
            return;
        }
        
        // Find where to insert (after </title> tag)
        const titleEnd = content.indexOf('</title>');
        if (titleEnd > -1) {
            // Insert favicon code after </title>
            const before = content.substring(0, titleEnd + 8); // Include </title>
            const after = content.substring(titleEnd + 8);
            content = before + faviconCode + after;
            
            // Write back to file
            fs.writeFileSync(filePath, content, 'utf8');
            updatedCount++;
            console.log(`✅ ${file}: Favicon code added!`);
        } else {
            console.log(`❌ ${file}: Could not find </title> tag`);
            errorCount++;
        }
    } catch (error) {
        console.log(`❌ ${file}: Error - ${error.message}`);
        errorCount++;
    }
});

console.log('\n' + '='.repeat(60));
console.log('📊 FINAL REPORT:');
console.log('='.repeat(60));
console.log(`✅ Updated: ${updatedCount} files`);
console.log(`⏭️  Skipped: ${skippedCount} files (already had favicon)`);
console.log(`❌ Errors: ${errorCount} files`);
console.log('='.repeat(60));

if (updatedCount > 0) {
    console.log('\n🎉 SUCCESS! Favicon code added to your HTML files.');
    console.log('\n📁 Your favicon files are in: img/favicon_io3/');
    console.log('🔗 Using relative paths: href="img/favicon_io3/filename"');
    
    console.log('\n🔍 Verify favicon files exist:');
    const checkFiles = [
        'img/favicon_io3/favicon.ico',
        'img/favicon_io3/favicon-16x16.png',
        'img/favicon_io3/favicon-32x32.png',
        'img/favicon_io3/apple-touch-icon.png',
        'img/favicon_io3/site.webmanifest'
    ];
    
    checkFiles.forEach(file => {
        const exists = fs.existsSync(path.join(__dirname, file));
        console.log(`${exists ? '✅' : '❌'} ${file} ${exists ? 'Found' : 'MISSING!'}`);
    });
    
    console.log('\n🚀 Next steps:');
    console.log('1. Run: npx live-server');
    console.log('2. Open each page in browser');
    console.log('3. Check browser tab icon appears');
    console.log('4. Clear cache if needed (Ctrl+Shift+R)');
} else if (skippedCount > 0) {
    console.log('\nℹ️  All files already have favicon code!');
    console.log('Check the HTML files for existing favicon links.');
}

console.log('\n💡 Tip: If favicon doesn\'t show, clear browser cache:');
console.log('   Chrome: Ctrl+Shift+Delete → Clear cached images and files');